// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, email string) (User, error)
	FindMany(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
