name: Lint and Build

on:
  pull_request:
    branches: [main, dev]

jobs:
  golint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Set GOPRIVATE environment variable
        run: echo "GOPRIVATE=github.com/eben92/*" >> $GITHUB_ENV

      - name: Configure Git for private repo access
        run: |
          git config --global url."https://${{ secrets.PERSONAL_TOKEN }}@github.com/".insteadOf https://github.com/

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: golint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Set GOPRIVATE environment variable
        run: echo "GOPRIVATE=github.com/eben92/*" >> $GITHUB_ENV

      - name: Configure Git for private repo access
        run: |
          git config --global url."https://${{ secrets.PERSONAL_TOKEN }}@github.com/".insteadOf https://github.com/

      - name: Test
        run: go test ./... -v
      - name: Build
        run: go build ./...
